### ISSUE TITLE
Set up Travis or another CI system

### ISSUE THREAD

**Issue by and-semakin** [alex-sherman/unsync#11]
It would be nice to see in pull requests if tests are failing or passing.

**Comment by alex-sherman** [comment]
I agree, unfortunately the time investment on this at the moment I think would not pay out. One giant issue standing in the way is that a fair number of the unit tests I've written will fail by dead locking and I haven't set timeouts on anything.

I think this is great for blue sky, especially if more people begin contributing, but for the moment I'll just leave this open as a "nice to have".

**Comment by and-semakin** [comment]
I had run test suite for ~400 times in a shell script on my machine. It seems to be stable, no errors happened. What tests do you suspect to be dead locking?

**Comment by alex-sherman** [comment]
I don't mean that the tests fail in a non-deterministic way, but when they do fail rather than the test getting marked as a failure, the test will just not complete. For instance, if you comment out the two lines below https://github.com/alex-sherman/unsync/blob/master/unsync/unsync.py#L105 the test that verifies that will, rather than reporting a failure, never complete.

**Comment by languitar** [comment]
Just as an idea: if you're using pytest as the test executor, [pytest timeout](https://pypi.org/project/pytest-timeout/) may provide a simple way to break in case something hangs for a period of time. Moreover, travis or whatever also have configurable timeouts for steps. That doesn't give the nicest results for test reporting, but is ok to detect that something bad has happened.

**Comment by alex-sherman** [comment]
Completed in #26 thanks again @Luttik!
