### ISSUE TITLE
Calling nested results() on futures produces InvalidStateError

### ISSUE THREAD

**Issue by Josephkready** [alex-sherman/unsync#28]
Running the following code produces an InvalidStateError. I built a simpler example below based on what I am trying to do. The idea is simple, having a unsync function that creates x number of tasks and returns the results of those tasks while inside the function. Either iterating through the list of tasks and calling result() or passing them into result_processor() raises an InvalidStateError. 

However, if I return the tasks instead of processing them inside caculation_tasks() and process them at the top level (either through iteration and result() or with the result_processor(tasks)) it works just fine. Returning the tasks to the top level could be problematic, and the service I am testing has a lot of nested function calls. 

```python
import time
import asyncio

from unsync import unsync

@unsync
async def async_continuation(new_num):
    """A preliminary result processor we'll chain on to the original task
       This will get executed wherever the source task was executed, in this
       case one of the threads in the ThreadPoolExecutor"""
    await asyncio.sleep(0.1)
    return new_num * 2, new_num

@unsync
async def caculation_tasks():
    tasks = []
    for x in range(1, 10):
        tasks.append(async_continuation(x))
    return result_processor(tasks).result()
    # return [x.result() for x in tasks]

@unsync
async def result_processor(tasks):
    """An async result aggregator that combines all the results
       This gets executed in unsync.loop and unsync.thread"""
    output = {}
    for task in tasks:
        num, res = await task
        output[num] = res
    return output


start = time.time()
results = caculation_tasks().result()
print(results)
print('Executed in {} seconds'.format(time.time() - start))
```

btw the guys at PythonBytes told me about this library and I am excited to play with it. 
https://pythonbytes.fm/episodes/show/184/too-many-ways-to-wait-with-await

**Comment by alex-sherman** [comment]
Thanks for taking the time to write this up! I added a more descriptive error message in 20ecd87dceb9e2a6f0597c2b279176fd2a483874 which says: "Calling result() in an unsync method is not allowed"

The crux of the problem is that if the unsync executor thread ever synchronously blocks on a future result (which requires the executor to run) then it will deadlock and never complete.

The solution is pretty easy, and generally good practice, just use `await` everywhere you can. For instance this is what I would do to fix your example:

```python
@unsync
async def caculation_tasks():
    tasks = []
    for x in range(1, 10):
        tasks.append(async_continuation(x))
    return [await task for task in tasks]
```

Thanks again for posting this, other users will definitely benefit from more descriptive errors as well!
