### ISSUE TITLE
Python 3.9.x compatability?

### ISSUE THREAD

**Issue by IdemenB** [alex-sherman/unsync#30]
Hi @alex-sherman , thanks a lot for this great API. I just wanted to give it a quick test with Python 3.9.0, but I get the following error. Number of concurrent processes do not change error (even 1 gives the same error).

Code:

```
from unsync import unsync
import time


@unsync(cpu_bound=True)
def heavy_calculation(num: int) -> int:

    print(f"iteration {num} started")
    return num ** num


if __name__ == "__main__":

    jobs = [heavy_calculation(i) for i in range(100)]

    for job in jobs:
        print(job.result())

    print(time.perf_counter())

```

Error:

```
Traceback (most recent call last):
  File "/Users/bbb/OneDrive/Docs/-- BW  --/-- Dev/SANDBOX/t_unsync.py", line 35, in <module>
    print(job.result())
  File "/Users/bbb/OneDrive/Docs/-- BW  --/-- Dev/SANDBOX/sandbox/lib/python3.9/site-packages/unsync/unsync.py", line 117, in result
    return self.concurrent_future.result(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/concurrent/futures/_base.py", line 440, in result
    return self.__get_result()
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/concurrent/futures/_base.py", line 389, in __get_result
    raise self._exception
KeyError: ('__main__', 'heavy_calculation')
(sandbox) bbb@Bariss-MacBook-Pro SANDBOX % /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/multiprocessing/resource_tracker.py:216: UserWarning: resource_tracker: There appear to be 5 leaked semaphore objects to clean up at shutdown
  warnings.warn('resource_tracker: There appear to be %d '
```

**Comment by alex-sherman** [comment]
Thanks for reporting this! Your example does currently run on Python3.9 under both Windows/Linux and I unfortunately do not have a Mac to test on.

I attempted a fix in ef46110. I think the problem was similar to on Windows where the module name for `__main__` gets changed to `__mp_main__` in multiprocess subprocesses. Could you try installing from source to see if that fixes your problem?

**Comment by IdemenB** [comment]
Thanks a lot for showing interest in the issue. I tried with various number of concurrent function runs, this time it is running up to some point and then freezes with the same error. Sample output with 10 runs:

(sandbox) BI@Bariss-MacBook-Pro SANDBOX % python test_unsync.py
```
program started
iteration 0 started
iteration 1 started
iteration 2 started
iteration 3 started
iteration 4 started
iteration 5 started
iteration 6 started
iteration 7 started
iteration 8 started
iteration 9 started
1
1
4
27
256
3125
46656
823543
16777216
387420489
0.212047804
(sandbox) barisidemen@Bariss-MacBook-Pro SANDBOX % /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/multiprocessing/resource_tracker.py:216: UserWarning: resource_tracker: There appear to be 50 leaked semaphore objects to clean up at shutdown
  warnings.warn('resource_tracker: There appear to be %d 
```

**Comment by alex-sherman** [comment]
I'm not able to reproduce this at the moment, but I do see an open issue for something like this on python.org: https://bugs.python.org/issue38842

Is it just the warning message? You say it runs to completion and then "freezes", did you have to end the process or does it just print the error and exit immediately? It does look like the program fully executed, the last line is the final `print`. In that case a work around may be to just ignore the error, since I can't track down a bug in `multiprocessing`.

**Comment by IdemenB** [comment]
I guess I was in the impression of a freeze because of a possible bug in the internal terminal of VS CODE; I just ran it in the Mac's regular terminal and there it is not freezing, just ending with the error message. What's interesting is that in both places the error message is cut short in the middle.

**Comment by dumblob** [comment]
Clicking on the link https://bugs.python.org/issue38842 above revealed the issue shall be solved.

I can't test whether unsync still has this issue on mac but if @IdemenB got a few minutes to test it and come back with results, that'd be great!

**Comment by IdemenB** [comment]
Hi @dumblob, I am now on Apple Silicon CPU and the code I previously posted in the first message is running fine now.
