### ISSUE TITLE
process_executor.py example on Windows 7 orphans the multiprocess kernels

### ISSUE THREAD

**Issue by OSHI7** [alex-sherman/unsync#35]
Hi,
Running the ```process_executor.py``` example in windows, does indeed create the parallel process, as evidenced by TaskManager, but the processes do not close on their own.
[Tested using PyCharm, on a Windows7 install, 64-bit OS)

Have I misconfigured, or am I missing something, or is this a limitation?
I can indeed see running the example creates the processes...
![image](https://user-images.githubusercontent.com/23404030/106414385-7b919d80-641a-11eb-944e-4ecef2f59a3d.png)

I would have thought each of the processes would have been closed/terminated after they completed.

*edit
Thinking/just realized: the onus is on me to set ```unsync.process_executor = None```, isn't it?
(The benefit then, is that the processingPool is setup and ready to go again, if it needs to be used, right?)

p.s. Thank you for sharing your excellent work.

**Comment by alex-sherman** [comment]
Yeah you're right on all accounts. The processes stay alive because there is relatively high overhead to start them. On my machine it takes 170ms to start the process pool and 30ms to close it.

My advice in general is to just leave the processes running, I don't think there's really a downside to them being idle. That said, the trick you described of setting `unsync.process_executor = None` seems to work if you prefer to stop them and don't mind the start/stop overhead.
